Repository lindb/lindb, pull requests merged in 2019-08, with the labels that each got.

#113 [feat:#1]:[replication:replicator]:replication
  broker/handler/write.go
  broker/rpc/broker_client.go
  broker/rpc/broker_server.go
  broker/rpc/broker_test.go
  broker/runtime.go
  broker/runtime_test.go
  config/broker.go
  config/storage.go
  models/node.go
  models/node_test.go
  pkg/fileutil/file.go
  pkg/fileutil/file_test.go
  pkg/fileutil/mmap.go
  pkg/queue/fanout.go
  pkg/queue/fanout_test.go
  pkg/queue/meta.go
  pkg/queue/queue.go
  pkg/queue/segment/factory.go
  pkg/queue/segment/factory_test.go
  replication/channel.go
  replication/channel_test.go
  replication/doc.go
  replication/replicator.go
  replication/replicator_test.go
  replication/sequence.go
  replication/sequence_test.go
  rpc/client.go
  rpc/client_pool.go
  rpc/pb/broker.proto
  rpc/pb/common.proto
  rpc/pb/storage.proto
  rpc/proto/broker/broker.pb.go
  rpc/proto/common/common.pb.go
  rpc/proto/storage/storage.pb.go
  rpc/proto/storage/storage_mock.pb.go
  rpc/rpc.go
  rpc/rpc_test.go
  service/storage.go
  storage/handler/query.go
  storage/handler/query_test.go
  storage/handler/write_test.go
  storage/handler/writer.go
  storage/runtime.go
  storage/runtime_test.go
  vendor/github.com/coreos/etcd/pkg/stringutil/stringutil.go
  vendor/modules.txt
Labels: feature

#115 [fix:#1][storage:handler]:fix query_test occasionally failed
  Makefile
  replication/replicator_test.go
  rpc/rpc.go
  rpc/rpc_test.go
  storage/handler/query_test.go
  storage/handler/write_test.go
Labels: bug

#125 [feat:#120][tsdb:indextbl]: series index table flusher
  README.md
  pkg/bufioutil/pool.go
  pkg/bufioutil/pool_test.go
  tsdb/doc.go
  tsdb/index/interface.go
  tsdb/indextbl/flusher.go
  tsdb/indextbl/flusher_test.go
  tsdb/indextbl/trie_tree.go
  tsdb/indextbl/trie_tree_test.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/helper_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_index.go
  tsdb/memdb/metric_store_index_test.go
  tsdb/memdb/metric_store_test.go
  tsdb/metrictbl/flusher.go
  tsdb/metrictbl/flusher_test.go
Labels: feature

#139 [feat:137][standalone]: implement cluster run as standalone mode
  .gitignore
  broker/runtime.go
  broker/runtime_test.go
  cmd/lind/broker.go
  cmd/lind/env.go
  cmd/lind/root.go
  cmd/lind/runner.go
  cmd/lind/standalone.go
  cmd/lind/storage.go
  cmd/main.go
  config/standalone.go
  coordinator/discovery/discovery.go
  coordinator/discovery/discovery_test.go
  coordinator/discovery/registry.go
  coordinator/elect/election.go
  coordinator/master.go
  coordinator/storage/task_executor_test.go
  pkg/fileutil/config.go
  pkg/fileutil/config_test.go
  pkg/server/service.go
  standalone/runtime.go
  standalone/runtime_test.go
  storage/runtime.go
  storage/runtime_test.go
Labels: feature

#174 [enhance:#173]:run standalone mode using default config file
  cmd/lind/standalone.go
Labels: enhancement

#180 [feat:#154][fe]: lindb web ui integration
  web/package.json
  web/src/components/BreadcrumbHeader.tsx
  web/src/components/Chart/Metric.tsx
  web/src/components/Chart/ViewBoard.tsx
  web/src/components/Layout/Footer.tsx
  web/src/components/Layout/Header.tsx
  web/src/components/Layout/SiderMenu.tsx
  web/src/components/TimePicker.tsx
  web/src/components/base/tips.tsx
  web/src/config/config.ts
  web/src/config/constant.ts
  web/src/config/menu.ts
  web/src/containers/Content/Content.tsx
  web/src/containers/Home/Home.tsx
  web/src/containers/Home/NodeInfo.tsx
  web/src/containers/Login/Login.tsx
  web/src/containers/Login/LoginBackground.tsx
  web/src/containers/Setting/Cluster.tsx
  web/src/containers/Setting/Database.tsx
  web/src/containers/Setting/NewDatabase.tsx
  web/src/index.tsx
  web/src/model/service.ts
  web/src/service/LinQLService.ts
  web/src/service/home.ts
  web/src/service/http.ts
  web/src/service/index.ts
  web/src/service/login.ts
  web/src/service/storage.ts
  web/src/style/index.less
  web/src/style/layout/index.less
  web/src/style/layout/login.less
  web/src/style/layout/sider.less
  web/src/style/style.less
  web/src/utils/URLUtil.ts
  web/src/utils/util.ts
  web/yarn.lock
Labels: feature

#181 [feat:#170][tsdb]: add series reader to support series.Filter
  pkg/stream/binary.go
  pkg/stream/binary_test.go
  query/series_search_test.go
  query/storage_plan_test.go
  tsdb/doc.go
  tsdb/indexdb/database.go
  tsdb/indexdb/database_test.go
  tsdb/indexdb/interface.go
  tsdb/indextbl/rank_select.go
  tsdb/indextbl/series_flusher.go
  tsdb/indextbl/series_flusher_test.go
  tsdb/indextbl/series_reader.go
  tsdb/indextbl/series_reader_test.go
  tsdb/indextbl/series_trie_tree.go
  tsdb/indextbl/series_trie_tree_test.go
  tsdb/memdb/constants.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_index.go
  tsdb/memdb/metric_store_index_test.go
  tsdb/memdb/metric_store_test.go
  tsdb/memdb/segment_store.go
  tsdb/memdb/timeseries_store.go
  tsdb/memdb/timeseries_store_test.go
  tsdb/series/error.go
  tsdb/series/interface.go
  tsdb/series/multi_ver.go
  tsdb/series/multi_ver_test.go
Labels: feature

#182 [feat:#179][sql]:encoding query statement
  .gitignore
  pkg/timeutil/time_range.go
  sql/stmt/expr.go
  sql/stmt/expr_test.go
  sql/stmt/query.go
  sql/stmt/query_test.go
  web/src/config/config.ts
Labels: feature

#186 [feat:#92][tsdb]: store mappings(seriesIDs -> tags) by ForwardIndex
  .gitignore
  go.mod
  pkg/bufpool/pool_test.go
  pkg/collections/bit_array.go
  pkg/collections/bit_array_test.go
  pkg/stream/reader.go
  pkg/stream/writer.go
  tsdb/doc.go
  tsdb/indexdb/database.go
  tsdb/indexdb/database_test.go
  tsdb/indexdb/interface.go
  tsdb/indextbl/forward_index_flusher.go
  tsdb/indextbl/forward_index_flusher_test.go
  tsdb/indextbl/forward_index_reader.go
  tsdb/indextbl/forward_index_reader_test.go
  tsdb/indextbl/inverted_index_flusher.go
  tsdb/indextbl/inverted_index_flusher_test.go
  tsdb/indextbl/inverted_index_reader.go
  tsdb/indextbl/inverted_index_reader_test.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_test.go
  tsdb/metrictbl/bit_array.go
  tsdb/metrictbl/bit_array_test.go
  tsdb/metrictbl/flusher.go
Labels: feature

#190 [feat:#20][kv]: compact job for kv store
  kv/compact_job.go
  kv/compact_job_test.go
  kv/compaction_state.go
  kv/compaction_state_test.go
  kv/family.go
  kv/family_test.go
  kv/flusher.go
  kv/flusher_test.go
  kv/merger.go
  kv/option.go
  kv/snapshot.go
  kv/store.go
  kv/store_test.go
  kv/table/builder.go
  kv/table/builder_test.go
  kv/table/cache.go
  kv/table/iterator.go
  kv/table/iterator_test.go
  kv/table/reader.go
  kv/table/reader_test.go
  kv/version/compact.go
  kv/version/compact_test.go
  kv/version/edit_log.go
  kv/version/edit_log_test.go
  kv/version/family_version.go
  kv/version/family_version_test.go
  kv/version/file_name.go
  kv/version/file_name_test.go
  kv/version/level.go
  kv/version/level_test.go
  kv/version/log.go
  kv/version/log_test.go
  kv/version/snapshot.go
  kv/version/snapshot_test.go
  kv/version/version.go
  kv/version/version_set.go
  kv/version/version_set_test.go
  kv/version/version_test.go
  pkg/logger/logger.go
  replication/channel.go
  tsdb/indexdb/database.go
  tsdb/indexdb/database_test.go
  tsdb/tblstore/forward_index_reader.go
  tsdb/tblstore/forward_index_reader_test.go
  tsdb/tblstore/inverted_index_reader.go
  tsdb/tblstore/inverted_index_reader_test.go
  tsdb/tblstore/metrics_meta_reader.go
  tsdb/tblstore/metrics_meta_reader_test.go
Labels: feature
