Repository lindb/lindb, pull requests merged in 2024-07, with the labels that each got.

#1031 [bug]: fix build docker fail
  Dockerfile
  Dockerfile-gh
  internal/linmetric/histogram_delta.go
  internal/linmetric/histogram_test.go
Labels: bug

#1032 [bug]: miss makezero in slice init
  .codecov.yml
  go.mod
  go.sum
  prometheus/engine.go
Labels: bug

#1033 [opt]: ignore histogram bucket if count<0
  aggregation/expression.go
  aggregation/fields/field.go
  aggregation/function/quantile.go
  aggregation/function/quantile_test.go
  app/broker/api/ingest/write.go
  pkg/collections/array_list.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
Labels: bug, enhancement

#1034 [bug]: fix get wrong data from memory database
  query/operator/metadata_lookup.go
  series/field/metas.go
  series/field/metas_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_filter.go
  tsdb/tblstore/metricsdata/reader.go
Labels: bug

#1035 [opt]: opt metric field memory store
  series/field/metas.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_test.go
  web/package.json
  web/vite.config.ts
  web/yarn.lock
Labels: enhancement

#1036 [feat]: memory database approximate memory size
  tsdb/memdb/compact_store.go
  tsdb/memdb/compact_store_test.go
  tsdb/memdb/data_point_buffer.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/time_series_index.go
Labels: feature

#1037 [feat]: cleanup memory metric meta/index if not used
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/index_database.go
  tsdb/memdb/index_database_test.go
  tsdb/memdb/metadata_database.go
  tsdb/memdb/metadata_database_test.go
  tsdb/memdb/metric_store.go
  tsdb/memdb/metric_store_test.go
  tsdb/memdb/time_series_index.go
  tsdb/memdb/time_series_index_test.go
Labels: feature

#1038 [bug]: fix wal ack invalid seq msg
  pkg/queue/consumer_group.go
  replica/replicator_local.go
  replica/replicator_remote.go
Labels: bug

#1039 [docs]: add Japanese README file
  README-ja.md
  README-zh_CN.md
  README.md
Labels: documentation

#1040 [enhance]: add self-monitoring metric/docs
  aggregation/function/quantile.go
  index/doc.go
  index/interface.go
  index/metric_index_database.go
  index/metric_index_database_test.go
  index/metric_meta_database.go
  index/metric_meta_database_test.go
  metrics/tsdb.go
  metrics/tsdb_test.go
  models/database.go
  pkg/option/tsdb_test.go
  series/metric/row_storage.go
  tsdb/data_family.go
  tsdb/database.go
  tsdb/database_test.go
  tsdb/engine.go
  tsdb/memdb/database.go
  tsdb/memdb/database_test.go
  tsdb/memdb/doc.go
  tsdb/memdb/index_database.go
  tsdb/memdb/index_database_test.go
  tsdb/memdb/metadata_database.go
  tsdb/memdb/metadata_database_test.go
  web/src/components/state/MemoryDatabaseView.tsx
Labels: enhancement

#1041 [feat]: add tsdb limits(namespace/metric/field/tag key/series)
  app/broker/api/ingest/write.go
  app/broker/api/ingest/write_test.go
  app/broker/api/prometheus/ingest/write.go
  config/global.go
  constants/errors.go
  coordinator/broker/state_machine_factory.go
  coordinator/broker/state_machine_factory_test.go
  coordinator/broker/state_manager.go
  coordinator/broker/state_manager_test.go
  coordinator/storage/state_manager_test.go
  index/benchmark_kv_store_test.go
  index/interface.go
  index/kv_store.go
  index/kv_store_test.go
  index/metric_index_database.go
  index/metric_index_database_test.go
  index/metric_meta_database.go
  index/metric_meta_database_test.go
  index/metric_schema_store.go
  index/metric_schema_store_test.go
  index/sequence.go
  index/sequence_test.go
  ingestion/influx/parser.go
  ingestion/influx/parser_test.go
  models/limits.go
  models/limits_test.go
  series/metric/row_flat_decoder.go
  series/metric/row_proto_converter.go
  tsdb/database.go
  tsdb/database_test.go
  tsdb/memdb/database_test.go
  tsdb/memdb/index_database.go
  tsdb/memdb/index_database_test.go
  tsdb/shard.go
  tsdb/shard_test.go
Labels: feature

#1043 [enhance]: remove installation guides from release notes
  .github/workflows/release.yml
Labels: enhancement
